adj_1 = input("Please submit an adjective")
verb_1 = input("Please submit a verb ending with s")
verb_2 = input("Please submit a past tense verb")
noun_1 = input("Submit a plural noun")
noun_2 = input("Submit a plural noun")
noun_3 = input("Submit a noun")
number_1 = input("Submit a number")
number_2 = input("Submit a number")
plural_noun_1 = input("Submit a plural noun")
plural_noun_2 = input("Submit another plural noun")
verb_4 = input("Submit a past tense verb")
adverb_1 = input("Submit an adverb ending in -ing")
verb_5 = input("Submit a verb")
name_1 = input("Submit a name")
group_1 = input("Submit a group name. ie Americans, Spanish")
group_2 = input("Submit another group name")
adj_2 = input("Submit an adjective")
noun_4 = input("Submit a noun")
verb_6 = input("Submit a verb")
verb_7 = input("Submit a verb")
adj_3 = input("Submit an adjective")
adj_4("Please submit an adjective")

print("Thanksgiving is a classic %s holiday that %s %s values. Everywhere I go, I can %s jokes" % (adj_1,verb_1,adj_1, verb_2))
print("calling it the %s of %s and %s, with some family on the side. That is actually how I would" % (noun_1, noun_2, noun_3))
print("describe my Thanksgivings. The %s Thanksgiving that many recognize was in %s," % (number_1, number_2))
print("a coming together of the %s and the %s. The %s had %s" % (group_1, group_2, group_1, adverb_1))
print("%s and it was a miracle they could even %s. Thankfully, a/an" % (verb_4, verb_5, adj_2))
print("%s man named %s helped end the conflict between the two groups, as" % (adj_3, name_1,))
print("well as teaching the %s how to survive in New England. %s was the %s to the" % (group_1, name_1, noun_5))
print("prayers and did his/her best to %s everything, and I believe he/she was successful. Later," % verb_6)
print("Presidents George Washington, Abraham Lincoln, and FDR would make Thanksgiving what we")
print("%s it as today, and all %s children enjoy getting the day off to be free." % (verb_7, adj_4))
