adj_1 = input("Please submit an adjective")
verb_1 = input("Please submit a verb ending with s")
verb_2 = input("Please submit another verb")
noun_1 = input("Submit a noun")
noun_2 = input("Submit a noun")
noun_3 = input("Submit a noun")
number_1 = input("Submit a number")
number_2 = input("Submit a number")
plural_noun_1 = input("Submit a plural noun")
plural_noun_2 = input("Submit another plural noun")


print("Thanksgiving is a classic %s holiday that %s %s values. I once %s a joke" % (adj_1,verb_1,adj_1, verb_2))
print("calling it the %s of %s and %s, with some family on the side. That is actually how I would" % (noun_1, noun_2, noun_3))
print("describe my Thanksgivings. The %s Thanksgiving that many %s recognize was in %s," % (number_1, adj_1, number_2)
print("a coming together of the Pilgrims and the Native Americans. The Pilgrims had endured")
print("extremely harsh conditions and it was a miracle they evened survived. Thankfully, a formerly")
print("enslaved Native named Squanto helped end the conflict between the tribes and the Pilgrims, as")
print("well as teaching the Pilgrims how to survive in New England. Squanto was the answer to the")
print("Pilgrims’ prayers and did his best to right everything, and I believe he was successful. Later,")
print("Presidents George Washington, Abraham Lincoln, and FDR would make Thanksgiving what we")
print("know it as today, and I am happy about that since I get a week off of school from it.")
